name: CI Kernel build

on:
  workflow_dispatch:
    inputs:
      PLACEHOLDER:
        description: 'idk'
        required: true
        default: ''
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    # You can use either of the ubuntu-18.04 or ubuntu-20.04 runner
    steps:

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install make perl gcc-aarch64-linux-gnu gcc-9-aarch64-linux-gnu libncurses5 gperf libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev python
        sudo apt -y install bc bison build-essential ccache curl flex git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
    - name: Setup SSH Keys
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12
        
    - name: Some actions
      run: |
        git config --global user.name "reocat"
        git config --global user.email "ng.ct_ml@tuta.io"
        git clone https://github.com/reocat/linux-msm8939-ido-pmos 
        cd linux-msm8939-ido-pmos
        make ARCH=arm64 msm8916_defconfig
        make -j16 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
        cd ..
        tar -czvf kernel.tar.gz linux-msm8939-ido-pmos
        split -b 1000M kernel.tar.gz "kernel.tgz.part"
      id: pwd

    - name: Upload to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ~Nya-nya, I love you onii-chan!~
        document: kernel.tgz.part*
